// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptionsTwo.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsTwo {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADLixSSqwLrTF7a25JmvvTYDaf_FwuO04',
    appId: '1:417866574560:web:917248817b9532af273e85',
    messagingSenderId: '417866574560',
    projectId: 'twoaccountfirebasetwo',
    authDomain: 'twoaccountfirebasetwo.firebaseapp.com',
    databaseURL: 'https://twoaccountfirebasetwo-default-rtdb.firebaseio.com',
    storageBucket: 'twoaccountfirebasetwo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnLY0qfjbtKS_x9mQlkLLVbn-v1hDEu8A',
    appId: '1:417866574560:android:50da728055f179ec273e85',
    messagingSenderId: '417866574560',
    projectId: 'twoaccountfirebasetwo',
    databaseURL: 'https://twoaccountfirebasetwo-default-rtdb.firebaseio.com',
    storageBucket: 'twoaccountfirebasetwo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9gDeM6wNDld3XK-MfsWlbmWHOZcAJyPw',
    appId: '1:417866574560:ios:0f298460db6b1343273e85',
    messagingSenderId: '417866574560',
    projectId: 'twoaccountfirebasetwo',
    databaseURL: 'https://twoaccountfirebasetwo-default-rtdb.firebaseio.com',
    storageBucket: 'twoaccountfirebasetwo.appspot.com',
    iosClientId: '417866574560-0v6k8c6iifpp45al4llib86i1mlvirfd.apps.googleusercontent.com',
    iosBundleId: 'com.example.twoaccountfirebasedifferentinjustproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9gDeM6wNDld3XK-MfsWlbmWHOZcAJyPw',
    appId: '1:417866574560:ios:0f298460db6b1343273e85',
    messagingSenderId: '417866574560',
    projectId: 'twoaccountfirebasetwo',
    databaseURL: 'https://twoaccountfirebasetwo-default-rtdb.firebaseio.com',
    storageBucket: 'twoaccountfirebasetwo.appspot.com',
    iosClientId: '417866574560-0v6k8c6iifpp45al4llib86i1mlvirfd.apps.googleusercontent.com',
    iosBundleId: 'com.example.twoaccountfirebasedifferentinjustproject',
  );
}
