// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCliNxV9LxBYHQjqzTHFiVqZEMaCkEU2eQ',
    appId: '1:232770714709:web:af44bc4e8ccb1f545e28dc',
    messagingSenderId: '232770714709',
    projectId: 'twoaccountfirebaseone',
    authDomain: 'twoaccountfirebaseone.firebaseapp.com',
    databaseURL: 'https://twoaccountfirebaseone-default-rtdb.firebaseio.com',
    storageBucket: 'twoaccountfirebaseone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8u3Gbt7plLQL7w7lUK-uT1nZHaTHfSxM',
    appId: '1:232770714709:android:3b24b0523aac7c415e28dc',
    messagingSenderId: '232770714709',
    projectId: 'twoaccountfirebaseone',
    databaseURL: 'https://twoaccountfirebaseone-default-rtdb.firebaseio.com',
    storageBucket: 'twoaccountfirebaseone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQmGvDXLn8A3mgDb9XMjH5ASo81s2FRdI',
    appId: '1:232770714709:ios:adc9a2f0c548d9dd5e28dc',
    messagingSenderId: '232770714709',
    projectId: 'twoaccountfirebaseone',
    databaseURL: 'https://twoaccountfirebaseone-default-rtdb.firebaseio.com',
    storageBucket: 'twoaccountfirebaseone.appspot.com',
    iosClientId: '232770714709-3dm6hnu3ed40vuhkv7upm912rhi32t9a.apps.googleusercontent.com',
    iosBundleId: 'com.example.twoaccountfirebasedifferentinjustproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQmGvDXLn8A3mgDb9XMjH5ASo81s2FRdI',
    appId: '1:232770714709:ios:adc9a2f0c548d9dd5e28dc',
    messagingSenderId: '232770714709',
    projectId: 'twoaccountfirebaseone',
    databaseURL: 'https://twoaccountfirebaseone-default-rtdb.firebaseio.com',
    storageBucket: 'twoaccountfirebaseone.appspot.com',
    iosClientId: '232770714709-3dm6hnu3ed40vuhkv7upm912rhi32t9a.apps.googleusercontent.com',
    iosBundleId: 'com.example.twoaccountfirebasedifferentinjustproject',
  );
}
